### ISSUE TITLE
Errors When Completing CVPR Registration

### ISSUE THREAD

**Issue by guilk** [openreview/openreview#55] opened 2022-11-08 18:25 UTC
**Describe the bug**
There is an error showing "Error: The field original is not allowed" when I try to complete the registration for CVPR. 

**To Reproduce**
1. In the "Complete Registration" page, we add the required fields.
2. We click "register for OpenReview" button.
3. There is an error "Error: The field original is not allowed" that shows at the top of the page.

**Expected behavior**
The registration should be finished without any issues.

**Screenshots**
![Screen Shot 2022-11-08 at 1 24 35 PM](https://user-images.githubusercontent.com/10675154/200645428-f3af4a29-6b39-4a48-aaf4-f5a49537af0a.png)

**Device information (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Additional context**

**Comment by melisabok** [comment] 2022-11-08 19:21
Thanks for reporting this, could you send us an email at info@openreview.net with the email address you are using to signup?

Melisa

**Comment by guilk** [comment] 2022-11-08 19:32
Thanks for your help! I have sent one email with the screenshot attached.

**Comment by KevinQian97** [comment] 2022-11-09 17:44
Hi, the one who encountered this problem is my advisor as well. I remember I added him to the author list, however, he disappeared in the current system. May I know if it's also caused by this problem or solving this problem? If so, can you help me solve that?

Thanks

**Comment by melisabok** [comment] 2022-11-09 18:00
Hi all, 

All the issues that require personal information to be investigated must be addressed by email. Please send us an email at info@openreview.net and we can help you. 

I'm closing this issue again.

Thanks for your understanding

Melisa

**Closed by melisabok** 2022-11-09 18:00 UTC

**Comment by KevinQian97** [comment] 2022-11-09 18:30
Hi Melisa, thanks! Just sent the email.
