### ISSUE TITLE
Cannot Edit Profile

### ISSUE THREAD

**Issue by kushalkafle** [openreview/openreview#19] opened 2022-03-01 17:55 UTC
**Describe the bug**
I am unable to make any changes to my profile due to a bug, possibly due to some deduplication error. When I hit "save profile changes" I get the error "username ~Kushal_Kafle1 is not a member of ~Kushal_Kafle2"; My profile id is the former (Kushal_Kafle1) and I am not aware of any duplicate accounts. Also, when I try to view the latter profile name, i.e., https://openreview.net/profile?id=~Kushal_Kafle2 , it redirects to https://openreview.net/profile?id=~Kushal_Kafle1 

**To Reproduce**
Steps to reproduce the behavior (For my account):

1. Go to edit profile
2. Make any or even no changes
3. Try to "save profile changes" in the bottom of th page

**Expected behavior**

Save successfully or provide a more helpful error to help me link these accounts; Only one of which I seem to have control over. 

**Screenshots**
![Error](https://user-images.githubusercontent.com/4214556/156222842-3c61f442-d1b7-43a4-8f84-c8ad77fca3dd.png)

**Device information (please complete the following information):**
 - OS: MacOS
 - Browser: Both Chrome and Safari tested
 - Version: Chrome Version: 98.0.4758.102 ; Safari Version 13.0.5 (15608.5.11)

**Additional context**

**Comment by xkopenreview** [comment] 2022-03-01 18:52
hi Kushal

it's caused by member mismatch between your accounts. some of them may be pre created for you and merged to  your account so that you are not aware of them.

it should be fixed, please try again.

**Comment by matthewmackay** [comment] 2022-03-08 05:36
I'm having the same problem with my profile (name: Matthew MacKay). Could you take a look and apply the same fix?

**Comment by matthewmackay** [comment] 2022-03-08 17:58
Thanks, it works now!

**Comment by carlosmondra** [comment] 2022-03-09 16:50
All profiles facing this issue should have been fixed by now.

**Closed by carlosmondra** 2022-03-09 16:50 UTC
